// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0ZBcQawoZR9KR7D5lluTahH3Se8LdEdY',
    appId: '1:870466193108:web:5e2cdce6c64d8cf3245d41',
    messagingSenderId: '870466193108',
    projectId: 'xaydal',
    authDomain: 'xaydal.firebaseapp.com',
    storageBucket: 'xaydal.firebasestorage.app',
    measurementId: 'G-4GQM41DJVS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuRhpS7Mqj_eGEpXrBFREkctitGnrZzgE',
    appId: '1:870466193108:android:0f08471c9b0a2ecd245d41',
    messagingSenderId: '870466193108',
    projectId: 'xaydal',
    storageBucket: 'xaydal.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3hGXXIsvlWlXioPAv23XKbUmHe-Dyrgw',
    appId: '1:870466193108:ios:4c19a0f2eca86dcb245d41',
    messagingSenderId: '870466193108',
    projectId: 'xaydal',
    storageBucket: 'xaydal.firebasestorage.app',
    iosBundleId: 'com.example.xyadalBucket',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3hGXXIsvlWlXioPAv23XKbUmHe-Dyrgw',
    appId: '1:870466193108:ios:4c19a0f2eca86dcb245d41',
    messagingSenderId: '870466193108',
    projectId: 'xaydal',
    storageBucket: 'xaydal.firebasestorage.app',
    iosBundleId: 'com.example.xyadalBucket',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0ZBcQawoZR9KR7D5lluTahH3Se8LdEdY',
    appId: '1:870466193108:web:d5f6a08dd942323e245d41',
    messagingSenderId: '870466193108',
    projectId: 'xaydal',
    authDomain: 'xaydal.firebaseapp.com',
    storageBucket: 'xaydal.firebasestorage.app',
    measurementId: 'G-Z6L39RT0P3',
  );

}